import os

os.system("python run_simtel.py --infile ~/Workspace/CTA/MCValidation/data/d2018-05-14_100mV_fw50pe/runlist_update.txt "
          " --outdir ~/Workspace/CTA/MCValidation/data/d2018-05-14_100mV_fw50pe/mcUpdate "
          " --nevents 10000 "
          " --angdist configs/ang_dist_mpik_flat_20deg.dat "
          " --distance 155.2 "
          " --camradius 30 "
          " --runSimTelarray "
          " --nsb 0.005 "
          " --discthresh File "
          " --extra_opts \"-C CAMERA_CONFIG_FILE=/home/armstrongt/Workspace/CTA/MCValidation/data/config/camera/02_cameraConfigFile/camera_CHEC-S_prototype_26042018.dat "
          " -C quantum_efficiency=/scratch/armstrongt/Workspace/CTA/MCValidation/data/config/camera/10_quantumEfficiency/S10362-11-050U-3V.txt "
          " -C discriminator_pulse_shape=/home/armstrongt/Workspace/CTA/MCValidation/data/config/camera/15_pulseShape/disc_shape_CHEC-S_27042018.dat "
          " -C fadc_pulse_shape=/home/armstrongt/Workspace/CTA/MCValidation/data/config/camera/15_pulseShape/pulse_CHEC-S_FADC_27042018.dat "
          " -C FADC_PEDESTAL=10000 "
          " -C FADC_SUM_OFFSET=15 "
          " -C TRIGGER_PIXELs=2 "
          " -C FADC_Sum_Bins=96 "
          " -C FADC_BINS=128 "
          " -C pm_voltage_variation=0 "
          " -C gain_variation=0.1 "
          " -C QE_variation=0.1 "
          " -C discriminator_amplitude=1 "
          " -C discriminator_gate_length=-8 "
          " -C discriminator_output_amplitude=1 "
          " -C discriminator_var_threshold=0.2 \"  "
          "--xdisp 0.0 --ydisp 0.0 --spec 398 ")